name = "gitroast-card"
main = "src/index.ts"
compatibility_date = "2026-07-26"
compatibility_flags = ["nodejs_compat"]

[cache]
enabled = true

[vars]
BACKEND_BASE_URL = "https://gitroast-api.onrender.com/api/v1"

[[routes]]
pattern = "card.gitroast.ai"
custom_domain = true

[[rules]]
type = "Data"
globs = ["**/*.woff"]
fallthrough = true

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

[env.preview]
name = "gitroast-card-preview"
routes = []

[env.preview.vars]
BACKEND_BASE_URL = "https://gitroast-api.onrender.com/api/v1"
